spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

# 配置mybatis规则
mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mybatis/mapper/*.xml
